In [ ]:
What does one need to do to use a module?
You need to import the module, then make a call to it



Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.

Pandas!

import pandas as pd

df = pd.read_vsv("dataset.csv")

print(df)

What is a benefit of using Exception handling?

it helps clarify what went wrong with program, especially if it is not a syntax error




1. NumPy arrays are like what Python data type?

Similar to lists


1. What is one of the main benefits of using NumPy arrays.

They are faster and more efficient to use


1. What is one of the main requirements about the 'dtype' of NumPy arrays?
all elements are the same

1. Of the 10 uses of NumPy, name 2.

Create arrays

reshape arrays


1. Name one of the other libraries we'll use with NumPy?
Pandas



1. What is the shape of NumPy arrays?
The shape of an array is the number of elements in each dimension.


1. What is a Tensor?
A tensor can be described as a n-dimensional numerical array

1. Name a reason why it's better using  NumPy for Data Analysis than using a Python List?


for better memory consumption

1. When creating an "empty" array, where do the elements come from?
An empty array is an array that has no value or is null

1. What does Pandas stand for?
Python Data Analysis Library 

1. What are the 2 collections used in Pandas?
namedtuple
Counter
defaultdict
OrderedDict
ChainMap
UserList
UserString
UserDict

1. Name 4 things Pandas can do for us.

 Data Cleansing 
 Data normalization 
 Data visualization 
 Data inspection


1. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?


1. What is a CSV

a comma seperated text file

1. When cleaning data what values do we not like in our data?
nulls

In [14]:
import numpy as np

arrayA = ([[25, 16]])
arrayB = ([[11, 2], [13, 4]])
arrayC = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arrayA, arrayB, arrayC), axis=0)
#print("Print arrCombo ...", newArray)


sortedArray = np.sort(newArray)

#print ("\nnewArray sorted ...\n", newArray)

reshapedArray = sortedArray.reshape(2, 2, 3)

print ("\n sortedArray reshaped ...\n", reshapedArray)

# print("new array")
# print(newArray)

(color1, color2) = reshapedArray

(blue, red) = color1
(green, purple) = color2

print("New colors")

print(blue)
print(red)
print(green)
print(purple)



 sortedArray reshaped ...
 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]
New colors
[16 25  2]
[11  4 13]
[ 7 81  5]
[ 6 11 12]


In [40]:
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three), axis=0)

#test print of comboArray
print(comboArray)
# print sec1 - the 2nd element
print(comboArray[1])

# print sec2 - all elements from the 3rd element to the last
print(comboArray[2:])


# print sec3 - all elements from the 4th to the 14th elements
print(comboArray[3:14])

# print sec4 - the last 6 elements
print(comboArray[-6:])

# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print(comboArray[16:4:-1])

# print sec6 - from #20 every even element to the end
print(comboArray[8::2])
# print sec7 - from the last element moving forward, every 5th element.
print(comboArray[::5])


[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
11
[12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[13 14 15 16 17 20 21 22 23 24 25]
[2 3 4 5 6 7]
[ 0 27 26 25 24 23 22 21 20 17 16 15]
[20 22 24 26  0  2  4  6]
[10 15 22 27  4]


In [11]:
from numpy import array
import numpy as np

arr1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

arr2 =  np.array([[17.0, 70.0, 10.7]])

print("broadcast add")
print(arr1 + arr2)

print("broadcast divide")
arrDivide = np.divide(arr1, arr2)
print(arrDivide)

print("broadcast multiply")
arrMultiply = np.multiply(arr1, arr2)
print(arrMultiply)

divisible_by_3 = arr1[arr1 % 3 == 0]
print("arr1 elements divisible_by_2 ...", divisible_by_3)


broadcast add
[[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]
broadcast divide
[[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]
broadcast multiply
[[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]
arr1 elements divisible_by_2 ... [ 0.  0. 30. 24. 15.]


In [ ]:
10. Using `Series`, create a `DataFrame` that looks like this:

    | Ingredients | Quantity | Unit |
    |----|----|----|
    | Flour | 4 | cups |
    | Milk | 1 | cup |
    | Eggs | 2 | large |
    | Spam | 1 | can |

    Name: Dinner, dtype: object

In [17]:
import pandas as pd
food = pd.DataFrame([["Flour", 4, "cups"], ["Milk", 1 , "cups"],["eggs", 2, "large"],["Spam", 1, "can"]], columns = ["Ingredients", "Quantity", "Unit" ])
print(food)                                                                                                           

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1   cups
2        eggs         2  large
3        Spam         1    can


In [25]:
import pandas as pd

studentData = pd.DataFrame( {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    })

studentData.insert(7, "Deserts", ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"], True )

studentData.sort_values(by = ['Name', 'address'])

print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [37]:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv', index=True)

df = pd.read_csv('cows_and_goats.csv')

print(df)



  Unnamed: 0  Cows  Goats
0     Year 1    12     22
1     Year 2    20     19


In [40]:



df = pd.DataFrame([["Broccoli", 1], ["Corn", 2], ["Carrot", 3]], columns=["Favorite Vegetable", "Rating"] )

df.to_csv('favVeggies.csv', index=False)

df = pd.read_csv('favVeggies.csv')

print(df)


   Unnamed: 0 Favorite Vegetable  Rating
0           0           Broccoli       1
1           1               Corn       2
2           2             Carrot       3
